export enum SensorType {
    AbstractSensor = 0,
    Temperature,
    Whisker,
    Pressure,
    Humidity,
    Oxygen,
    WaterMeter,
    Switch,
    StaticPressure,
    Bin,
    WindDirection,
    WindSpeed,
    Current,
    Ammonia,
    CO2,
    WaterLevel,
    PressureGuage,
    VoltageSensor,
    CO,
    RainPrecipitationSensor,
    GasMeterSensor,
    ElectricMeterSensor,
    EC,
    PH,
    Moisture,
    ORP,
    Weight,
    PPM,
    RemoteSensor = 256 //For Future Virtual should start at 128, Remote will start a 256
}